version: "3"
services:
  db:
    image: "clickhouse/clickhouse-server"
    container_name: 'db'
    restart: 'always'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9000:9000"
    volumes:
      - 'clickhouse_data:/var/lib/clickhouse/'
      - 'clickhouse_log:/var/log/clickhouse-server/'
    environment:
      CLICKHOUSE_USER: 'admin'
      CLICKHOUSE_PASSWORD: 'root'

  redis:
    image: redis
    container_name: 'redis'
    restart: 'always'
    ports:
      - "6379:6379"



volumes:
  clickhouse_data:
  clickhouse_log:
